server:
  port: 8762
spring:
  application:
    name: provider-hello #服务的名字
  datasource:
    url: jdbc:mysql://152.136.84.40:3306/1812-1
    username: root
    password: PFcNiwOp
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #链接注册中心的地址

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com:
      mr: debug